port: 7890
socks-port: 7891
mode: rule
log-level: debug  #åœ¨è°ƒè¯•ç»“æœåï¼Œæ”¹ä¸ºerroræˆ–warnï¼Œå‡å°‘æ—¥å¿—è¾“å‡ºã€‚
external-controller: '0.0.0.0:9090'
external-ui: /usr/local/etc/clash/ui
secret: 123456
tun:
  enable: true
  stack: system
  device: tun_3000
  mtu: 9000
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver: 
    - 127.0.0.1:5335  #æŒ‡å‘mosdnsç›‘å¬åœ°å€
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "+.push.apple.com"
proxies:
- name: RN-vless               
  type: vless
  server: 88.88.88.88.88                           
  port: 2443                                
  uuid: 34c18fad-ec2f-4e75-aea6-d78e6d45a550   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com                 
  reality-opts: 
    public-key: f1qn-AHx1S35vIjCgVqjad9Yc45RDXfn7bCTRF5koSU    
    short-id: '96770c21'                    
  client-fingerprint: chrome                  
- name: RN-ws                        
  type: vmess
  server: 88.88.88.88.88                        
  port: 3443                                     
  uuid: 34c18fad-ec2f-4e75-aea6-d78e6d45a550       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "34c18fad-ec2f-4e75-aea6-d78e6d45a550-vm"                             
    headers:
      Host: www.bing.com                     
- name: RN-hy2                          
  type: hysteria2                                      
  server: 88.88.88.88.88                               
  port: 9443                                
  password: 34c18fad-ec2f-4e75-aea6-d78e6d45a550                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true
- name: RN-tuic5                          
  server: 88.88.88.88.88                      
  port: 8443                                    
  type: tuic
  uuid: 34c18fad-ec2f-4e75-aea6-d78e6d45a550       
  password: 34c18fad-ec2f-4e75-aea6-d78e6d45a550   
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true
- name: BW-vless               
  type: vless
  server: 88.88.88.88.88                           
  port: 2443                                
  uuid: 03f32af4-750c-4869-b3a2-ce35592fa744   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com                 
  reality-opts: 
    public-key: tTIbe-TH9pGCmUCI8jklnY8LNscaTIk-xYWVbDSD_yQ    
    short-id: '73ef4cb6'                    
  client-fingerprint: chrome                  
- name: BW-ws                        
  type: vmess
  server: 88.88.88.88.88                        
  port: 3443                                     
  uuid: 03f32af4-750c-4869-b3a2-ce35592fa744       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "03f32af4-750c-4869-b3a2-ce35592fa744-vm"                             
    headers:
      Host: www.bing.com                     
- name: BW-hy2                           
  type: hysteria2                                      
  server: 88.88.88.88.88                               
  port: 9443                                
  password: 03f32af4-750c-4869-b3a2-ce35592fa744                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true
- name: BW-tuic5                            
  server: 88.88.88.88.88                      
  port: 8443                                    
  type: tuic
  uuid: 03f32af4-750c-4869-b3a2-ce35592fa744       
  password: 03f32af4-750c-4869-b3a2-ce35592fa744   
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true  
- name: CD-vless               
  type: vless
  server: 88.88.88.88.88                           
  port: 2443                                
  uuid: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: www.yahoo.com                 
  reality-opts: 
    public-key: hNOGsu1ZgaqWqZsiF65ZDukKdYdLd87i2E8a5mTSeiw    
    short-id: 'd36a9946'                      
  client-fingerprint: chrome                  
- name: CD-ws                         
  type: vmess
  server: 88.88.88.88.88                        
  port: 3443                                     
  uuid: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "a2c842d2-e629-4d48-b1ea-d16ccbdc75d9-vm"                             
    headers:
      Host: www.bing.com                     
- name: CD-hy2                            
  type: hysteria2                                      
  server: 88.88.88.88.88                               
  port: 9443                                
  password: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true
- name: CD-tuic5                            
  server: 88.88.88.88.88                      
  port: 8443                                    
  type: tuic
  uuid: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9       
  password: a2c842d2-e629-4d48-b1ea-d16ccbdc75d9   
  alpn: [h3]
  disable-sni: true
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  sni: www.bing.com                                
  skip-cert-verify: true
proxy-groups:
- name: è´Ÿè½½å‡è¡¡
  type: load-balance
  url: https://www.gstatic.com/generate_204
  interval: 300
  strategy: round-robin
  proxies:
    - RN-vless                             
    - RN-ws
    - RN-hy2
    - RN-tuic5
    - CD-vless                             
    - CD-ws
    - CD-hy2
    - CD-tuic5
    - BW-vless                             
    - BW-ws
    - BW-hy2
    - BW-tuic5
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
    - RN-vless                             
    - RN-ws
    - RN-hy2
    - RN-tuic5
    - CD-vless                             
    - CD-ws
    - CD-hy2
    - CD-tuic5
    - BW-vless                             
    - BW-ws
    - BW-hy2
    - BW-tuic5	    
- name: ğŸŒé€‰æ‹©ä»£ç†èŠ‚ç‚¹
  type: select
  proxies:
    - è´Ÿè½½å‡è¡¡                                         
    - è‡ªåŠ¨é€‰æ‹©
    - DIRECT
    - RN-vless                             
    - RN-ws
    - RN-hy2
    - RN-tuic5
    - CD-vless                             
    - CD-ws
    - CD-hy2
    - CD-tuic5
    - BW-vless                             
    - BW-ws
    - BW-hy2
    - BW-tuic5 
rules:
  - DOMAIN,v2rayssr.com,ğŸŒé€‰æ‹©ä»£ç†èŠ‚ç‚¹
  - DOMAIN,bulianglin.com,ğŸŒé€‰æ‹©ä»£ç†èŠ‚ç‚¹ 
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,ğŸŒé€‰æ‹©ä»£ç†èŠ‚ç‚¹

