name: auto_v2dat

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-unpack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: 'false'

    - name: Build v2dat
      run: |
        set -e
        git clone https://github.com/urlesistiana/v2dat.git
        cd v2dat
        go build
        ls -l v2dat

    - name: Download geoip.dat and verify checksum
      run: |
        set -e
        echo "Downloading geoip.dat..."
        curl --connect-timeout 5 -m 60 --ipv4 -kfSLo "geoip.dat" "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
        
        echo "Downloading geoip.dat.sha256sum..."
        curl --connect-timeout 5 -m 10 --ipv4 -kfSLo "geoip.dat.sha256sum" "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat.sha256sum"
        
        echo "Verifying checksum..."
        sha256sum --check "geoip.dat.sha256sum"

    - name: Download geosite.dat and verify checksum
      run: |
        set -e
        echo "Downloading geosite.dat..."
        curl --connect-timeout 5 -m 120 --ipv4 -kfSLo "geosite.dat" "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
        
        echo "Downloading geosite.dat.sha256sum..."
        curl --connect-timeout 5 -m 10 --ipv4 -kfSLo "geosite.dat.sha256sum" "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat.sha256sum"
        
        echo "Verifying checksum..."
        sha256sum --check "geosite.dat.sha256sum"

    - name: Unpack geosite and geoip
      run: |
        set -e
        ./v2dat/v2dat unpack geoip -o mosdns/domains -f private geoip.dat
        ./v2dat/v2dat unpack geoip -o mosdns/domains -f cn geoip.dat
        ./v2dat/v2dat unpack geosite -o mosdns/domains -f cn geosite.dat
        ./v2dat/v2dat unpack geosite -o mosdns/domains -f gfw geosite.dat
        ./v2dat/v2dat unpack geosite -o mosdns/domains -f 'geolocation-!cn' geosite.dat
        ./v2dat/v2dat unpack geosite -o mosdns/domains -f category-ads-all geosite.dat

    - name: Set up git
      run: |
        set -e
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config user.name "${{ secrets.GIT_USER_NAME }}"

    - name: Commit and push
      run: |
        set -e
        git add mosdns/domains/
        if ! git diff --staged --quiet mosdns/domains/; then
          git commit -m "Automated geoip/site update"
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

